base_model: EleutherAI/pythia-1.4b-deduped
model_type: GPTNeoXForCausalLM
tokenizer_type: AutoTokenizer
load_in_8bit: true
datasets:
  - path: ./data/alpaca_data_gpt4.jsonl
    type: alpaca
  - path: ./data/vicuna_cleaned.jsonl
    type: sharegpt
  - path: ./data/gpt4-instruct-similarity-0.6-dataset.jsonl
    type: gpteacher
  - path: ./data/roleplay-similarity_0.6-instruct-dataset.jsonl
    type: gpteacher
val_set_size: 0.05
adapter: lora
sequence_len: 2048
lora_r: 16
lora_alpha: 32
lora_dropout: 0.05
lora_target_modules:
  - q_proj
  - v_proj
wandb_project:
wandb_watch:
wandb:run_name:
wandb_log_model: checkpoint
output_dir: ./lora-alpaca
batch_size: 128
micro_batch_size: 8
num_epochs: 5
learning_rate: 0.0003
train_on_inputs: false
bf16: True
fp16: True
resume_from_checkpoint:
local_rank:
deepspeed:
