name: E2E
on:
  workflow_dispatch:

jobs:
  e2e-test:
    runs-on: [self-hosted, gpu]
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.10"]
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
          cache: 'pip' # caching pip dependencies

      - name: Install dependencies
        run: |
          pip3 install -e .
          pip3 install flash-attn
          pip3 install -r requirements-tests.txt

      - name: Run e2e tests
        run: |
          pytest tests/e2e/
