name: publish pypi

on:
  push:
    branches:
      - "main"

jobs:
  pypi-publish:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/axolotl-ai
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    with:
      verbose: true
    steps:
      # retrieve your distributions here
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
